spring:
  application:
    name: GruzovichkofObratkaBot
  datasource:
    url: jdbc:postgresql://localhost:5432/obratka
    username: postgres
    password: 123321
    driver-class-name: org.postgresql.Driver
  jpa:
      database: postgresql
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          format_sql: true
  sql:
      init:
        mode: always
bot:
  token: 6490264832:AAGIlybsx7n41U6jlZvZhMwrQMRg942rzSM
  name: GfObratkaBot