DROP TABLE IF EXISTS drivers, cars, destinations CASCADE;

CREATE TABLE IF NOT EXISTS drivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_telegram_id VARCHAR UNIQUE NOT NULL,
    driver_fio VARCHAR(255) NOT NULL,
    driver_telephone VARCHAR(11) UNIQUE NOT NULL,
    driver_created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS cars (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_stamp VARCHAR NOT NULL,
    car_number VARCHAR UNIQUE NOT NULL,
    car_type VARCHAR NOT NULL,
    car_length VARCHAR NOT NULL,
    car_weight VARCHAR NOT NULL,
    car_height VARCHAR NOT NULL,
    car_volume VARCHAR NOT NULL,
    car_type_of_loading VARCHAR[] NOT NULL,
    car_load_opacity VARCHAR NOT NULL,
    driver_id BIGINT NOT NULL,
    CONSTRAINT fk_cars_to_driver
            FOREIGN KEY(driver_id) REFERENCES drivers(id) ON DELETE CASCADE,
    driver_created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS destinations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_from VARCHAR NOT NULL,
    destination_to VARCHAR NOT NULL,
    destination_date_arrival VARCHAR NOT NULL,
    destination_created_at TIMESTAMP NOT NULL,
    driver_id BIGINT NOT NULL,
    CONSTRAINT fk_destinations_to_driver
        FOREIGN KEY(driver_id) REFERENCES drivers(id) ON DELETE CASCADE
);
