DROP TABLE IF EXISTS drivers CASCADE;

CREATE TABLE IF NOT EXISTS drivers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        driver_telegram_id VARCHAR UNIQUE NOT NULL,
        driver_fio VARCHAR(255) NOT NULL,
        driver_telephone VARCHAR(11) UNIQUE NOT NULL,
        driver_type_car_body VARCHAR(100) NOT NULL,
        driver_car_body_dimensions VARCHAR NOT NULL,
        driver_load_opacity INT NOT NULL,
        driver_created_at TIMESTAMP NOT NULL
);